### ISSUE TITLE
/tmp/cs.MM_raw.txt

### ISSUE THREAD

**Issue by asifdadra** [PaperRepos/Today_arxiv#1]
Hi I am getting the error:

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cs.MM_raw.txt'

**Comment by jheo4** [comment]
Hi Thanks for your interest in this repo. Sorry for late response -- I just found this.

I just updated the codes and please check whether it works with the commit 5579246226969fe00aa400a851bc12eaca8e74d5

If it does not work with the latest commit, can you let me know which OS are you on and your execution environment? 

Thanks,
